# Map drives numbers to lcec slaves
# names will determine the name of the component pins
hal_402_device_mgr:
    # update rate of publisher in Hz
    update_rate: 10
    drives:
        name: "drive"
        instances: [1, 2, 3, 4, 5, 6]
    slaves:
        name: "lcec.0"
        wait_on_pinname: "warning"
        wait_timeout: 20
        instances: [0, 1, 2, 3, 4, 5]
    # additional signals can be connected.
