# Map drives numbers to lcec slaves
# names will determine the name of the component pins
hal_402_device_mgr:
    # update rate of publisher in Hz
    update_rate: 10
    drives:
        name: "drive"
        instances: [1, 2, 3, 4, 5, 6]
    slaves:
        name: "lcec.0"
        wait_on_pinname: "warning"
        wait_timeout: 20
        instances: [0, 1, 2, 3, 4, 5]
    # additional signals can be connected: ['pin', 'signal']
    signals:
        - ["hal_402_mgr.drive_1.enable-operation", "joint1_operation_enabled_402"]
        - ["hal_402_mgr.drive_2.enable-operation", "joint2_operation_enabled_402"]
        - ["hal_402_mgr.drive_3.enable-operation", "joint3_operation_enabled_402"]
        - ["hal_402_mgr.drive_4.enable-operation", "joint4_operation_enabled_402"]
        - ["hal_402_mgr.drive_5.enable-operation", "joint5_operation_enabled_402"]
        - ["hal_402_mgr.drive_6.enable-operation", "joint6_operation_enabled_402"]
